### ISSUE TITLE
help with setup?

### ISSUE THREAD

**Issue by alexeinz** [Yoda-x/ha-zha-new#31]
I updated the bellows and zigpy as specified but get following error... any chance you can point me to the right solution....
Error during setup of component zha_new
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 142, in _async_setup_component
    result = await component.async_setup(hass, processed_config)
  File "/home/homeassistant/.homeassistant/custom_components/zha_new.py", line 217, in async_setup
    await ezsp_.connect(usb_path, baudrate)
  File "/srv/homeassistant/lib/python3.6/site-packages/bellows/ezsp.py", line 29, in connect
    self._gw = await uart.connect(device, baudrate, self)
  File "/srv/homeassistant/lib/python3.6/site-packages/bellows/uart.py", line 267, in connect
    xonxoff=True,
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 212, in coro
    res = func(*args, **kw)
  File "/srv/homeassistant/lib/python3.6/site-packages/serial_asyncio/__init__.py", line 410, in create_serial_connection
    ser = serial.serial_for_url(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/serial/__init__.py", line 88, in serial_for_url
    instance.open()
  File "/srv/homeassistant/lib/python3.6/site-packages/serial/serialposix.py", line 288, in open
    self._update_rts_state()
  File "/srv/homeassistant/lib/python3.6/site-packages/serial/serialposix.py", line 627, in _update_rts_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_RTS_str)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by alexeinz** [comment]
sorry, something was grabbing port
