### ISSUE TITLE
Error during setup at Loading application state in homeassistant

### ISSUE THREAD

**Issue by jdeglopper** [Yoda-x/ha-zha-new#34]
Hi - I'm running your ha-zha-new component with a custom Docker build including your version of bellows and zigpy.  This worked with a previous build - code from maybe 8 weeks ago - but with a current pull, I get errors on the second start of homeassistant.  If I remove the zigbee DB file, I don't get an error.   I don't think there's any sensitive data in the zigbee DB, so I'm attaching that as well. 
[zigbee.zip](https://github.com/Yoda-x/ha-zha-new/files/2161577/zigbee.zip)

Any thoughts?  The DB file seems to open normally in other sqlite tools.

```2018-07-03 09:44:10 INFO (MainThread) [homeassistant.setup] Setting up zha_new
2018-07-03 09:44:10 DEBUG (MainThread) [zigpy.appdb] Loading application state from /config/zigbee_new.db
2018-07-03 09:44:11 ERROR (MainThread) [homeassistant.setup] Error during setup of component zha_new
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 143, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/zha_new.py", line 220, in async_setup
    APPLICATION_CONTROLLER = ControllerApplication(ezsp_, database)
  File "/usr/local/lib/python3.6/site-packages/bellows/zigbee/application.py", line 22, in __init__
    super().__init__(database_file=database_file)
File "/usr/local/lib/python3.6/site-packages/zigpy/application.py", line 24, in __init__
    self._dblistener.load()
  File "/usr/local/lib/python3.6/site-packages/zigpy/appdb.py", line 213, in load
    ep = dev.endpoints[endpoint_id]
KeyError: 1

```

I comment out bellows and zigpy in requirements_all.txt, add git to the packages in setup_docker_prereqs, and build with the following Dockerfile:

```
FROM python:3.6
LABEL maintainer="Paulus Schoutsen <Paulus@PaulusSchoutsen.nl>"

# Uncomment any of the following lines to disable the installation.
#ENV INSTALL_TELLSTICK no
#ENV INSTALL_OPENALPR no
#ENV INSTALL_FFMPEG no
#ENV INSTALL_LIBCEC no
#ENV INSTALL_PHANTOMJS no
#ENV INSTALL_SSOCR no
#ENV INSTALL_IPERF3 no

VOLUME /config

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy build scripts
COPY virtualization/Docker/ virtualization/Docker/
RUN virtualization/Docker/setup_docker_prereqs

# Install hass component dependencies
COPY requirements_all.txt requirements_all.txt
# Uninstall enum34 because some dependencies install it but breaks Python 3.4+.
# See PR #8103 for more info.
RUN pip3 install --no-cache-dir -r requirements_all.txt && \
    pip3 install --no-cache-dir mysqlclient psycopg2 uvloop cchardet cython && \
    pip3 install --upgrade git+https://github.com/Yoda-x/bellows.git && \
    pip3 install --upgrade git+https://github.com/Yoda-x/zigpy.git

# Copy source
COPY . .

CMD [ "python", "-m", "homeassistant", "--config", "/config" ]
```

**Comment by jdeglopper** [comment]
Resolved by removing the zigbee DB and making sure I had a clean shutdown.  Still a mystery how I had a corrupted DB in the first place, though.
