### ISSUE TITLE
AttributeError: 'Device' object has no attribute 'rss'

### ISSUE THREAD

**Issue by KLUSEK** [Yoda-x/ha-zha-new#43]
After trying your fresh commit and trying to add Xiaomi Aqara Door sensor I'm getting this:

```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/homeassistant/.homeassistant/custom_components/binary_sensor/zha_new.py", line 73, in async_setup_platform
    entity = await _make_sensor(device_class, discovery_info)
  File "/home/homeassistant/.homeassistant/custom_components/binary_sensor/zha_new.py", line 104, in _make_sensor
    cluster_key=OnOff.ep_attribute)
  File "/home/homeassistant/.homeassistant/custom_components/binary_sensor/zha_new.py", line 263, in __init__
    super().__init__(device_class, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/binary_sensor/zha_new.py", line 169, in __init__
    super().__init__(**kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/zha_new.py", line 700, in __init__
    self._device_state_attributes['rssi'] = endpoint.device.rss
AttributeError: 'Device' object has no attribute 'rss'
```

Looks like you ate "i" in the name of attribute ;)

bellows                 0.7.0-Y
zigpy                   0.1.2-Y
zigpy-xbee              0.1.1

**Comment by Yoda-x** [comment]
please pull again. you were too fast

**Comment by KLUSEK** [comment]
Thanks :) It's okay now
