### ISSUE TITLE
Missing file "zigpy.quirks"

### ISSUE THREAD

**Issue by MYeager1967** [Yoda-x/ha-zha-new#85]
I just decided to upgrade to the current version (have avoided it because I haven't had time to reconfigure everything) and I'm getting this error. I'm running in a docker container on a Synology NAS and it ran just fine under 0.87.1. We've fixed a few issues before but this is a new one for me. I even looked back at the messages we've exchanged before...

Wed May 08 2019 20:16:21 GMT-0400 (Eastern Daylight Time)
Error setting up entry /dev/ttyUSB2 for zha
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/config_entries.py", line 309, in async_setup
    hass, self)
  File "/usr/src/app/homeassistant/components/zha/__init__.py", line 92, in async_setup_entry
    import zhaquirks  # noqa
  File "/usr/local/lib/python3.7/site-packages/zhaquirks/__init__.py", line 3, in <module>
    from zigpy.quirks import CustomCluster
ModuleNotFoundError: No module named 'zigpy.quirks'

**Comment by Yoda-x** [comment]
looks like the original zha  code is loaded "/usr/src/app/homeassistant/components/zha/init.py" by the config entries. Did you used the orignal zha? 
what hass version you run in the docker container? 
I run the new version in a venv on 0.92.1. 
Sorry for any inconvenience...

**Comment by MYeager1967** [comment]
When I get home today, I'll wipe the image and try again. I think it did
try to load the original zha at first. Might have buggered trying to use
yours afterwards. Would be nice if it would just work in the first place....

**Comment by MYeager1967** [comment]
Ok, I deleted the container and even the base image. Re-downloaded the image and still have exactly the same error. The entities are showing up and the zha_new controller entity is there, but I'm not sure that it's reading the devices at this point. I love upgrading... Here's my config for zha_new...

zha_new:
  usb_path: /dev/ttyUSB2
  database_path: /config/zigbee.db

**Comment by MYeager1967** [comment]
I'm seriously considering writing this experiment with using Zigbee door sensors off and start looking for an alternative. I couldn't find a z-wave sensor that was worth a shit and now I can't seem to get these back online either. The two that were linked to the radio before still show up and report in, I just get no status on them (don't change from closed to open or anything). The other one I tried to remove and rejoin acts like it's joined, but disconnects. Any suggestions?

**Comment by Yoda-x** [comment]
ok, delete inside the ".storage" directory the core.config.entries file and if you have a  core.entity_registry file, these also. 
There are many more places where hass stores data now. The problem is that if you used zha before it stores information for devices related as to ZHA, and even if you switched to zha_new this information is still there and reloaded on startup with the 'old' ZHA domain code. There it breaks.
If you have other core.x.x files and it does not help, delete these also. 
BTW, on the main git page the first sentence is never ever to use the configuration menu for zha...

**Comment by MYeager1967** [comment]
I renamed all the core.whatever files and let it recreate them. My devices are showing up, but I won't know for a bit if they're working again. I still can't get the one sensor to completely pair again. Your code seems to be solid, and I haven't had any issue until I upgrade HA. As for the integration, I tried it on a copy of my configuration directory. I also deleted the container when it didn't work. Almost wondering if my Zigbee stick is having an issue...

**Comment by Yoda-x** [comment]
It seems the 0x0500 cluster is not created during init.
Can you please send a log  when you start Hass. Then all devices gets created...
A custom_components debug.

**Comment by Yoda-x** [comment]
PS:no need to start from scretch. Just enable debug and do a restart..

**Comment by MYeager1967** [comment]
Is there a way to enable debug on just this one component? I tried the way that the wiki spells out, but it kept giving me an error. Anyhow, I found this:

2019-05-13 16:34:31 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] node config for 00:0d:6f:00:0b:f2:68:85-1: {}
2019-05-13 16:34:31 DEBUG (SyncWorker_5) [custom_components.alexa_media] m*********7@gmail.com: last_called changed:  to {'serialNumber': 'G************BWM', 'timestamp': 1557765187285}
2019-05-13 16:34:31 DEBUG (MainThread) [custom_components.zha_new] Import DH 3014 failed: ("No module named 'custom_components.device.3014'",)
2019-05-13 16:34:31 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] pre call _custom_endpoint_init: {}
2019-05-13 16:34:31 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] no call _custom_endpoint_init: 3014
2019-05-13 16:34:31 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] node config for 00:0d:6f:00:0b:f2:68:85-1: {}
2019-05-13 16:34:31 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] config reports skipped for 00:0d:6f:00:0b:f2:68:85, already joined 

It goes to the sensor that I tried to rejoin that isn't showing as joined. The button clicks on the sensor itself says it's not joined. That's probably an easy fix.

Also found this:

2019-05-13 16:34:42 DEBUG (SyncWorker_1) [homeassistant.util.json] JSON file not found: /config/custom_components/zha_new/.translations/binary_sensor.en.json

which I believe could be the issue...

Anything specific I should be looking for?

**Comment by Yoda-x** [comment]
please try 
```
logger:
  default: error
  logs:
    custom_components.zha_new: debug
```
to enable debug only for zha_new

There are no translations included with zha_new, this is normal.

Can you describe what you did so far to repair the device?

**Comment by MYeager1967** [comment]
Well, I deleted the files you mentioned earlier, that didn't do it. I even deleted the database file for the zigbee devices. It rebuilt it and it looks the same as it did before. I'm stabbing in the dark... I have no idea what is wrong so anything I do to fix it is just random guess. Any idea what the .translations file issue is? I don't have that folder at all and doesn't appear I had it in the previous installation either. Sorry I'm not much help. Between working and other things, I don't have much time to work this problem. I'll retry the logging in the morning...

**Comment by MYeager1967** [comment]
I added the line to the configuration file and this is what I got.

2019-05-15 20:07:00 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-05-15 20:07:00 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for zha_new which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea] device init for <class 'str'>(3010)(00:0d:6f:00:0b:1f:27:6e) -> Endpoints: [0, 1], already joined 
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea:0] endpoint init
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea:1] endpoint init
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea:1] node config for 00:0d:6f:00:0b:1f:27:6e-1: {}
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] Import DH 3010 failed: ("No module named 'custom_components.device.3010'",)
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea:1] pre call _custom_endpoint_init: {}
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea:1] no call _custom_endpoint_init: 3010
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea:1] node config for 00:0d:6f:00:0b:1f:27:6e-1: {}
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea:1] config reports skipped for 00:0d:6f:00:0b:1f:27:6e, already joined 
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea:1] 2:profile 260, component: binary_sensor cluster:[{0, 1280, 1030, 7}, {768, 1280, 4, 5, 6, 8}] in_clusters: {0: <zigpy.zcl.clusters.general.Basic object at 0x7f94c6ba2be0>, 1: <zigpy.zcl.clusters.general.PowerConfiguration object at 0x7f94c6c179b0>, 3: <zigpy.zcl.clusters.general.Identify object at 0x7f94c6c17c50>, 1280: <zigpy.zcl.clusters.security.IasZone object at 0x7f94c6c17780>, 32: <zigpy.zcl.clusters.general.PollControl object at 0x7f94c6c17a58>}
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea:1] Single Cluster: set()
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea:1]general entity:260, component:binary_sensor clusters:{0, 1, 32, 3, 1280}<->set()
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea:1] Create general entity:00:0d:6f:00:0b:1f:27:6e
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x5dea] Exit device init 00:0d:6f:00:0b:1f:27:6e
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x1105] device init for <class 'str'>(3014)(00:0d:6f:00:0b:f2:68:85) -> Endpoints: [0, 1], already joined 
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x1105:0] endpoint init
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] endpoint init
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] node config for 00:0d:6f:00:0b:f2:68:85-1: {}
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] Import DH 3014 failed: ("No module named 'custom_components.device.3014'",)
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] pre call _custom_endpoint_init: {}
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] no call _custom_endpoint_init: 3014
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] node config for 00:0d:6f:00:0b:f2:68:85-1: {}
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] config reports skipped for 00:0d:6f:00:0b:f2:68:85, already joined 
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] 2:profile 260, component: binary_sensor cluster:[{0, 1280, 1030, 7}, {768, 1280, 4, 5, 6, 8}] in_clusters: {0: <zigpy.zcl.clusters.general.Basic object at 0x7f94c6c17198>, 1: <zigpy.zcl.clusters.general.PowerConfiguration object at 0x7f94c6c172e8>, 3: <zigpy.zcl.clusters.general.Identify object at 0x7f94c6c179e8>, 1280: <zigpy.zcl.clusters.security.IasZone object at 0x7f94c6c0af60>, 32: <zigpy.zcl.clusters.general.PollControl object at 0x7f94c6c0aac8>}
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] Single Cluster: set()
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1]general entity:260, component:binary_sensor clusters:{0, 1, 32, 3, 1280}<->set()
2019-05-15 20:07:27 DEBUG (MainThread) [custom_components.zha_new] [0x1105:1] Create general entity:00:0d:6f:00:0b:f2:68:85
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x1105] Exit device init 00:0d:6f:00:0b:f2:68:85
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3] device init for <class 'str'>(3010)(00:0d:6f:00:0b:f2:3f:81) -> Endpoints: [0, 1], already joined 
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3:0] endpoint init
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3:1] endpoint init
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3:1] node config for 00:0d:6f:00:0b:f2:3f:81-1: {}
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3:1] pre call _custom_endpoint_init: {}
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3:1] no call _custom_endpoint_init: 3010
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3:1] node config for 00:0d:6f:00:0b:f2:3f:81-1: {}
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3:1] config reports skipped for 00:0d:6f:00:0b:f2:3f:81, already joined 
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3:1] 2:profile 260, component: binary_sensor cluster:[{0, 1280, 1030, 7}, {768, 1280, 4, 5, 6, 8}] in_clusters: {0: <zigpy.zcl.clusters.general.Basic object at 0x7f94c6c0a7b8>, 1: <zigpy.zcl.clusters.general.PowerConfiguration object at 0x7f94c6c0a780>, 3: <zigpy.zcl.clusters.general.Identify object at 0x7f94c6c0a940>, 1280: <zigpy.zcl.clusters.security.IasZone object at 0x7f94c6bfa518>, 32: <zigpy.zcl.clusters.general.PollControl object at 0x7f94c6bfaa20>}
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3:1] Single Cluster: set()
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3:1]general entity:260, component:binary_sensor clusters:{0, 1, 32, 3, 1280}<->set()
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3:1] Create general entity:00:0d:6f:00:0b:f2:3f:81
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new] [0x85d3] Exit device init 00:0d:6f:00:0b:f2:3f:81
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x85d3:1] initialize cluster listeners: -[(0, <zigpy.zcl.clusters.general.Basic object at 0x7f94c6c0a7b8>), (1, <zigpy.zcl.clusters.general.PowerConfiguration object at 0x7f94c6c0a780>), (32, <zigpy.zcl.clusters.general.PollControl object at 0x7f94c6bfaa20>), (3, <zigpy.zcl.clusters.general.Identify object at 0x7f94c6c0a940>), (1280, <zigpy.zcl.clusters.security.IasZone object at 0x7f94c6bfa518>)]- 
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x85d3:1] exit make binary-sensor 
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] set Entity object: <class 'custom_components.zha_new.binary_sensor.BinarySensor'>-00:0d:6f:00:0b:f2:3f:81_1 
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] Return binary_sensor init-cluster {0: <zigpy.zcl.clusters.general.Basic object at 0x7f94c6c0a7b8>, 1: <zigpy.zcl.clusters.general.PowerConfiguration object at 0x7f94c6c0a780>, 3: <zigpy.zcl.clusters.general.Identify object at 0x7f94c6c0a940>, 1280: <zigpy.zcl.clusters.security.IasZone object at 0x7f94c6bfa518>, 32: <zigpy.zcl.clusters.general.PollControl object at 0x7f94c6bfaa20>}
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x5dea:1] initialize cluster listeners: -[(0, <zigpy.zcl.clusters.general.Basic object at 0x7f94c6ba2be0>), (1, <zigpy.zcl.clusters.general.PowerConfiguration object at 0x7f94c6c179b0>), (32, <zigpy.zcl.clusters.general.PollControl object at 0x7f94c6c17a58>), (3, <zigpy.zcl.clusters.general.Identify object at 0x7f94c6c17c50>), (1280, <zigpy.zcl.clusters.security.IasZone object at 0x7f94c6c17780>)]- 
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x5dea:1] exit make binary-sensor 
2019-05-15 20:07:28 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] set Entity object: <class 'custom_components.zha_new.binary_sensor.BinarySensor'>-00:0d:6f:00:0b:1f:27:6e_1 
2019-05-15 20:07:29 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] Return binary_sensor init-cluster {0: <zigpy.zcl.clusters.general.Basic object at 0x7f94c6ba2be0>, 1: <zigpy.zcl.clusters.general.PowerConfiguration object at 0x7f94c6c179b0>, 3: <zigpy.zcl.clusters.general.Identify object at 0x7f94c6c17c50>, 1280: <zigpy.zcl.clusters.security.IasZone object at 0x7f94c6c17780>, 32: <zigpy.zcl.clusters.general.PollControl object at 0x7f94c6c17a58>}
2019-05-15 20:07:29 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x1105:1] initialize cluster listeners: -[(0, <zigpy.zcl.clusters.general.Basic object at 0x7f94c6c17198>), (1, <zigpy.zcl.clusters.general.PowerConfiguration object at 0x7f94c6c172e8>), (32, <zigpy.zcl.clusters.general.PollControl object at 0x7f94c6c0aac8>), (3, <zigpy.zcl.clusters.general.Identify object at 0x7f94c6c179e8>), (1280, <zigpy.zcl.clusters.security.IasZone object at 0x7f94c6c0af60>)]- 
2019-05-15 20:07:29 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x1105:1] exit make binary-sensor 
2019-05-15 20:07:29 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] set Entity object: <class 'custom_components.zha_new.binary_sensor.BinarySensor'>-00:0d:6f:00:0b:f2:68:85_1 
2019-05-15 20:07:29 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] Return binary_sensor init-cluster {0: <zigpy.zcl.clusters.general.Basic object at 0x7f94c6c17198>, 1: <zigpy.zcl.clusters.general.PowerConfiguration object at 0x7f94c6c172e8>, 3: <zigpy.zcl.clusters.general.Identify object at 0x7f94c6c179e8>, 1280: <zigpy.zcl.clusters.security.IasZone object at 0x7f94c6c0af60>, 32: <zigpy.zcl.clusters.general.PollControl object at 0x7f94c6c0aac8>}
2019-05-15 20:07:29 DEBUG (MainThread) [custom_components.zha_new] entity_list added: {'binary_sensor.binary_sensor_nyce_3010_0bf23f81_1': <Entity binary_sensor.binary_sensor_nyce_3010_0bf23f81_1: off>}
2019-05-15 20:07:29 DEBUG (MainThread) [custom_components.zha_new] Restore state for binary_sensor.binary_sensor_nyce_3010_0bf23f81_1:
2019-05-15 20:07:29 DEBUG (MainThread) [custom_components.zha_new] entity_list added: {'binary_sensor.binary_sensor_nyce_3010_0bf23f81_1': <Entity binary_sensor.binary_sensor_nyce_3010_0bf23f81_1: off>, 'binary_sensor.binary_sensor_nyce_3010_0b1f276e_1': <Entity binary_sensor.binary_sensor_nyce_3010_0b1f276e_1: off>}
2019-05-15 20:07:29 DEBUG (MainThread) [custom_components.zha_new] Restore state for binary_sensor.binary_sensor_nyce_3010_0b1f276e_1:
2019-05-15 20:07:29 DEBUG (MainThread) [custom_components.zha_new] entity_list added: {'binary_sensor.binary_sensor_nyce_3010_0bf23f81_1': <Entity binary_sensor.binary_sensor_nyce_3010_0bf23f81_1: off>, 'binary_sensor.binary_sensor_nyce_3010_0b1f276e_1': <Entity binary_sensor.binary_sensor_nyce_3010_0b1f276e_1: off>, 'binary_sensor.binary_sensor_nyce_3014_0bf26885_1': <Entity binary_sensor.binary_sensor_nyce_3014_0bf26885_1: off>}
2019-05-15 20:07:29 DEBUG (MainThread) [custom_components.zha_new] Restore state for binary_sensor.binary_sensor_nyce_3014_0bf26885_1:

I'm seriously hoping something catches your eye as being the problem. I'm going to try to rejoin the one sensor and see what that throws in the log... Here's the result of that. 

2019-05-15 20:15:04 INFO (MainThread) [custom_components.zha_new] Permitting joins for 60s
2019-05-15 20:15:50 DEBUG (MainThread) [custom_components.zha_new] Device joined: 00:0d:6f:00:0b:f2:68:85:
2019-05-15 20:15:50 DEBUG (MainThread) [custom_components.zha_new] Device initialized: 00:0d:6f:00:0b:f2:68:85:
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] Attribute report received on cluster [0x0000:5:]=b'3014'
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] read attribute: {'model': b'3014'}
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] Attribute report received on cluster [0x0000:4:]=b'NYCE'
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] read attribute: {'manufacturer': b'NYCE'}
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] manufacturer: type(<class 'bytes'>) b'NYCE'
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] manufacturer: type(<class 'str'>) NYCE
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] model: type(<class 'bytes'>) b'3014'
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] model: type(<class 'str'>) 3014
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] discover_endpoint_info:{'manufacturer': 'NYCE', 'model': '3014'}
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1] device init for <class 'str'>(3014)(00:0d:6f:00:0b:f2:68:85) -> Endpoints: [0, 1], new join 
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1:0] endpoint init
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1:1] endpoint init
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1:1] node config for 00:0d:6f:00:0b:f2:68:85-1: {}
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1:1] pre call _custom_endpoint_init: {}
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1:1] no call _custom_endpoint_init: 3014
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1:1] node config for 00:0d:6f:00:0b:f2:68:85-1: {}
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1:1] config reports skipped for 00:0d:6f:00:0b:f2:68:85, no reports configured 
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1:1] 2:profile 260, component: binary_sensor cluster:[{0, 1280, 1030, 7}, {768, 1280, 4, 5, 6, 8}] in_clusters: {0: <zigpy.zcl.clusters.general.Basic object at 0x7f94c6c17198>, 1: <zigpy.zcl.clusters.general.PowerConfiguration object at 0x7f94c6c172e8>, 3: <zigpy.zcl.clusters.general.Identify object at 0x7f94c6c179e8>, 1280: <zigpy.zcl.clusters.security.IasZone object at 0x7f94c6c0af60>, 32: <zigpy.zcl.clusters.general.PollControl object at 0x7f94c6c0aac8>}
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1:1] Single Cluster: set()
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1:1]general entity:260, component:binary_sensor clusters:{0, 1, 32, 3, 1280}<->set()
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1:1] Create general entity:00:0d:6f:00:0b:f2:68:85
2019-05-15 20:15:51 DEBUG (MainThread) [custom_components.zha_new] [0x20a1] Exit device init 00:0d:6f:00:0b:f2:68:85
2019-05-15 20:15:53 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] write cie:[[<WriteAttributesStatusRecord status=Status.SUCCESS attrid=0>]]
2019-05-15 20:15:53 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x20a1:1] initialize cluster listeners: -[(0, <zigpy.zcl.clusters.general.Basic object at 0x7f94c6c17198>), (1, <zigpy.zcl.clusters.general.PowerConfiguration object at 0x7f94c6c172e8>), (32, <zigpy.zcl.clusters.general.PollControl object at 0x7f94c6c0aac8>), (3, <zigpy.zcl.clusters.general.Identify object at 0x7f94c6c179e8>), (1280, <zigpy.zcl.clusters.security.IasZone object at 0x7f94c6c0af60>)]- 
2019-05-15 20:15:53 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x20a1:1] bind input-cluster 0: [0]
2019-05-15 20:15:54 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x20a1:1] bind input-cluster 1: [0]
2019-05-15 20:15:54 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x20a1:1] bind input-cluster 32: [0]
2019-05-15 20:15:55 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x20a1:1] bind input-cluster 3: [0]
2019-05-15 20:15:55 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x20a1:1] bind input-cluster 1280: [0]
2019-05-15 20:15:55 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] [0x20a1:1] exit make binary-sensor 
2019-05-15 20:15:55 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] entity exist,remove it: RegistryEntry(entity_id='binary_sensor.binary_sensor_nyce_3014_0bf26885_1', unique_id='00:0d:6f:00:0b:f2:68:85_1', platform='zha_new', name='Garage Door Sensor', device_id='00:0d:6f:00:0b:f2:68:85', config_entry_id=None, disabled_by=None)
2019-05-15 20:15:55 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] set Entity object: <class 'custom_components.zha_new.binary_sensor.BinarySensor'>-00:0d:6f:00:0b:f2:68:85_1 
2019-05-15 20:15:56 DEBUG (MainThread) [custom_components.zha_new.binary_sensor] Return binary_sensor init-cluster {0: <zigpy.zcl.clusters.general.Basic object at 0x7f94c6c17198>, 1: <zigpy.zcl.clusters.general.PowerConfiguration object at 0x7f94c6c172e8>, 3: <zigpy.zcl.clusters.general.Identify object at 0x7f94c6c179e8>, 1280: <zigpy.zcl.clusters.security.IasZone object at 0x7f94c6c0af60>, 32: <zigpy.zcl.clusters.general.PollControl object at 0x7f94c6c0aac8>}
2019-05-15 20:15:56 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback <function async_track_state_change.<locals>.state_change_listener at 0x7f94d64840d0>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/usr/src/app/homeassistant/helpers/event.py", line 82, in state_change_listener
    event.data.get('new_state'))
  File "/usr/src/app/homeassistant/core.py", line 333, in async_run_job
    target(*args)
  File "/usr/src/app/homeassistant/helpers/event.py", line 108, in template_condition_listener
    hass.async_run_job(action, entity_id, from_s, to_s)
  File "/usr/src/app/homeassistant/core.py", line 333, in async_run_job
    target(*args)
  File "/usr/src/app/homeassistant/components/automation/template.py", line 34, in template_listener
    }, context=to_s.context))
AttributeError: 'NoneType' object has no attribute 'context'
2019-05-15 20:15:56 DEBUG (MainThread) [custom_components.zha_new] entity_list added: {'binary_sensor.binary_sensor_nyce_3010_0bf23f81_1': <Entity binary_sensor.binary_sensor_nyce_3010_0bf23f81_1: off>, 'binary_sensor.binary_sensor_nyce_3010_0b1f276e_1': <Entity binary_sensor.binary_sensor_nyce_3010_0b1f276e_1: off>, 'binary_sensor.binary_sensor_nyce_3014_0bf26885_1': <Entity binary_sensor.binary_sensor_nyce_3014_0bf26885_1: off>}
2019-05-15 20:15:56 DEBUG (MainThread) [custom_components.zha_new] Restore state for binary_sensor.binary_sensor_nyce_3014_0bf26885_1:

There's a handled exception in the log for the attempted join. The sensor didn't complete the join, but HA thinks it did.

**Comment by Yoda-x** [comment]
the exception is from the automation component. do you have any scripts related to the garage sensor?

**Comment by MYeager1967** [comment]
Yes. I can turn them off. I don't understand why they would be throwing any
errors though. The entity for the sensor exists but always shows as not
tripped because the status isn't updating. I'll turn them off in the
morning and see what happens.

**Comment by Yoda-x** [comment]
btw, how you do the re-pairing? do you remove the device first from HA with "zha_new.remove" ? This is needed as otherwise zha_new will not write any configurations to the NYCE device. 
I don't know why the automation creates a traceback, but disabling it will remove one possible option. It may the cause or not.

**Comment by MYeager1967** [comment]
Can you provide an example of the data portion for the zha_new.remove? I always seem to have issues with those. I'm willing to try anything at this point...  :-)

**Comment by Yoda-x** [comment]
can you try this file for the [3014](https://gist.github.com/Yoda-x/0f28cb76c35de9466a1cdbcda36a1d37)
Just put it in the device directory and do a hass restart. 
It should fix the "unknown Client2Server" messages and then it should handle the alarms again....

**Comment by Yoda-x** [comment]
please get a fresh master and let me know if you see a battery-level and/or voltage... 
level may a little bit low. newest cluster library documentation says values are reported as 0.5% ticks (60 -> 30%) Not sure if older devices do it this way. But at least you should see something.

**Comment by MYeager1967** [comment]
I have all kinds of data now. It's not in the same format for all three sensors nor is it all there on all of them, but it's there.  That said, if I were to remove and rejoin the other two sensors, I'm willing to bet they'd all be the same. Looks like all that's missing is the battery voltage reading on the original two. Excellent work!!!

**Comment by Yoda-x** [comment]
Did you repaired the two others? Look they all now the same?

**Comment by MYeager1967** [comment]
I haven't removed and re-paired them yet but it looks like the only difference now is I don't have the battery voltage on the other two. Looks like you got it. Excellent work. 😀
